export const platformSectionsScript = String.raw`
let platformTab='organizations',userOffset=0,userQuery='';
async function platformSection(tab){
 platformTab=tab;
 for(const button of document.querySelectorAll('[data-platform-tab]')){button.classList.toggle('active',button.dataset.platformTab===tab);button.setAttribute('aria-current',button.dataset.platformTab===tab?'page':'false')}
 el('list-view').classList.toggle('hidden',tab!=='organizations'||!!selected);el('detail-view').classList.toggle('hidden',tab!=='organizations'||!selected);el('platform-section').classList.toggle('hidden',tab==='organizations');
 if(tab==='organizations'){await render();return}
 el('breadcrumb-current').textContent=tab[0].toUpperCase()+tab.slice(1);const root=el('platform-section');root.textContent='Loading…';
 try{if(tab==='users')await platformUsers(root);if(tab==='analytics')await platformAnalytics(root);if(tab==='security')await platformSecurity(root)}catch(error){root.textContent='Unable to load this section.';note(error.message||String(error),true)}
}
async function userRequest(action,userId,values={}){
 const session=check(await db.auth.getSession()).session;if(!session)throw Error('Sign in again.');
 const {data,error}=await db.functions.invoke('platform-admin-users',{body:{action,userId,...values}});
 if(error){let message=error.message;try{message=(await error.context.json()).error||message}catch{}throw Error(message)}if(data?.error)throw Error(data.error);return data;
}
async function platformUsers(root){
 const result=check(await db.rpc('platform_users',{search_input:userQuery,offset_input:userOffset}));
 root.innerHTML='<h1>Users</h1><form id="user-search" class="row"><label>Search users<input id="user-query" type="search" value="'+esc(userQuery)+'" placeholder="Name or email"></label><button>Search</button></form><p>'+esc(result.total)+' accounts</p><table><thead><tr><th>User</th><th>Organizations / roles</th><th>Classes</th><th>Status</th><th></th></tr></thead><tbody>'+result.users.map(u=>'<tr><td>'+esc(u.display_name||'Unnamed user')+'<br>'+esc(u.email||'—')+'</td><td>'+esc(u.organizations.map(o=>o.name+' ('+o.role+')').join(', ')||'Standalone')+(u.platform_admin?' · Platform admin':'')+'</td><td>'+esc(u.classes)+'</td><td>'+esc(u.deletion_pending?'Cleanup pending':u.account_deleted_at?'Deleted':'Active')+'</td><td>'+(!u.account_deleted_at?'<button data-edit-user="'+u.id+'">Edit profile</button><button class="danger" data-delete-user="'+u.id+'">Delete user</button>':u.deletion_pending?'<button class="danger" data-delete-user="'+u.id+'">Retry deletion</button>':'')+'</td></tr>').join('')+'</tbody></table><div class="row"><button id="users-prev" '+(!userOffset?'disabled':'')+'>Previous</button><span>'+Math.min(userOffset+1,result.total)+'–'+Math.min(userOffset+50,result.total)+' of '+result.total+'</span><button id="users-next" '+(userOffset+50>=result.total?'disabled':'')+'>Next</button></div>';
 el('user-search').onsubmit=async e=>{e.preventDefault();userQuery=el('user-query').value.trim();userOffset=0;await platformSection('users')};
 el('users-prev').onclick=async()=>{userOffset=Math.max(0,userOffset-50);await platformSection('users')};el('users-next').onclick=async()=>{userOffset+=50;await platformSection('users')};
 root.querySelectorAll('[data-edit-user]').forEach(b=>b.onclick=()=>{const u=result.users.find(u=>u.id===b.dataset.editUser);openAdminForm({title:'Edit user profile',fields:[{name:'display_name',label:'Display name',value:u.display_name||'',required:true},{name:'email',label:'Sign-in email',type:'email',value:u.email||'',required:true}],onSubmit:async values=>{await userRequest('update',u.id,values);note('User profile updated.');await platformSection('users')}})});
 root.querySelectorAll('[data-delete-user]').forEach(b=>b.onclick=()=>{const u=result.users.find(u=>u.id===b.dataset.deleteUser);openAdminForm({title:'Delete '+(u.display_name||u.email),description:'Sign-in will be removed and the profile anonymized. Memberships will be removed; historical work remains. Standalone classes owned by this user close. Transfer sole organization ownership first.',fields:[{name:'confirmation',label:'Type '+u.email+' to confirm',required:true}],submitLabel:'Delete user',onSubmit:async values=>{if(values.confirmation!==u.email)throw Error('Email does not match.');await userRequest('delete',u.id,values);note('User deleted.');await platformSection('users')}})});
}
function bars(rows,label,value){const max=Math.max(1,...rows.map(r=>Number(r[value])||0));return '<div role="img" aria-label="'+esc(value)+' comparison">'+rows.map(r=>'<div style="display:grid;grid-template-columns:minmax(100px,1fr) 3fr 90px;gap:12px;align-items:center;margin:12px 0"><span>'+esc(r[label])+'</span><div style="height:12px;background:var(--line);border-radius:4px"><div style="height:100%;width:'+Math.max(0,Number(r[value])/max*100)+'%;background:var(--accent);border-radius:4px"></div></div><strong>'+esc(Number(r[value]).toLocaleString())+'</strong></div>').join('')+'</div>'}
async function platformAnalytics(root){
 root.innerHTML='<h1>Analytics</h1><div class="row"><label>Period<select id="analytics-days"><option value="7">Last 7 days</option><option value="30" selected>Last 30 days</option><option value="90">Last 90 days</option></select></label><label>Organization<select id="analytics-org"><option value="">All organizations, including standalone classes</option>'+organizations.map(o=>'<option value="'+o.id+'">'+esc(o.name)+'</option>').join('')+'</select></label></div><div id="analytics-data"></div>';
 async function refresh(){const data=check(await db.rpc('platform_analytics',{days_input:Number(el('analytics-days').value),organization_id_input:el('analytics-org').value||null}));el('analytics-data').innerHTML='<div style="margin-top:24px">'+[['Users',data.users],['Active students',data.activeUsers],['Classes',data.classes],['Projects',data.projects],['Sessions',data.sessions],['Known cost','$'+(data.cost/1000000).toFixed(2)],['Unpriced events',data.unpriced]].map(([label,value])=>'<div class="stat"><strong>'+esc(value)+'</strong>'+esc(label)+'</div>').join('')+'</div><h2>Daily sessions</h2>'+(data.daily.length?bars(data.daily,'day','sessions'):'<p>No sessions in this period.</p>')+'<h2>Daily token usage</h2>'+bars(data.daily,'day','tokens')+'<h2>Model usage</h2>'+bars(data.models,'model','tokens')+'<p>Activity describes recorded sessions, not grades or measured learning outcomes. Model combinations reflect sessions using more than one model.</p>'}
 for(const id of ['analytics-days','analytics-org'])el(id).onchange=()=>refresh().catch(error=>note(error.message,true));await refresh();
}
async function platformSecurity(root){
 let coverage='';try{const result=await userRequest('sync-security','');coverage=result.available?'Failed-login logs checked '+new Date(result.checkedAt).toLocaleString():result.message;}catch(error){coverage=error.message;}
 check(await db.rpc('refresh_platform_security'));
 const rows=check(await db.rpc('platform_security_alerts'));
 root.innerHTML='<h1>Security</h1><p>'+esc(coverage)+'</p><p>Review signals in context. Alerts do not automatically restrict an account.</p><label>Review status<select id="security-filter"><option value="open">Open</option><option value="all">All</option><option value="resolved">Resolved</option><option value="dismissed">Dismissed</option></select></label><div id="security-rows"></div><p>Showing up to 200 recent alerts. Chat alerts contain categories only, never excerpts.</p>';
 function draw(){const filtered=rows.filter(r=>el('security-filter').value==='all'||r.status===el('security-filter').value);el('security-rows').innerHTML='<table><thead><tr><th>When</th><th>Account / class</th><th>Signal</th><th>Severity / status</th><th>Review</th></tr></thead><tbody>'+filtered.map(r=>'<tr><td>'+esc(new Date(r.occurred_at).toLocaleString())+'</td><td>'+esc(r.profiles?.email||r.profiles?.display_name||'Unknown account')+'<br>'+esc(r.classes?.name||'')+'</td><td>'+esc(r.summary)+'<br><small>'+esc(r.source)+'</small></td><td>'+esc(r.severity)+' · '+esc(r.status)+'</td><td><button data-review="'+r.id+'" data-status="resolved">Resolve</button><button data-review="'+r.id+'" data-status="dismissed">Dismiss</button><button data-review="'+r.id+'" data-status="open">Reopen</button></td></tr>').join('')+'</tbody></table>';root.querySelectorAll('[data-review]').forEach(b=>b.onclick=async()=>{try{check(await db.rpc('review_security_alert',{alert_id_input:b.dataset.review,status_input:b.dataset.status}));await platformSection('security')}catch(error){note(error.message,true)}})}
 el('security-filter').onchange=draw;draw();
}
for(const button of document.querySelectorAll('[data-platform-tab]'))button.onclick=()=>platformSection(button.dataset.platformTab);
`;
